Jovem Programador WEB/Models/Aluno.cs
using Microsoft.VisualBasic;
using System.ComponentModel.DataAnnotations;

namespace Jovem_Programador_WEB.Models
{
    public class Aluno
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public int Idade { get; set; }
        public string Matricula { get; set; }
        public DateTime? DataNascimento { get; set; }
        public string Cep { get; set; }
    }
}

Jovem Programador WEB/Models/Endereco.cs
using Microsoft.AspNetCore.Mvc.ApplicationModels;

namespace Jovem_Programador_WEB.Models
{
    public class Endereco
    {
       public string logradouro { get; set; }
       public string complemento { get; set; }
       public string bairro { get; set; }
       public string localidade { get; set; }
        public string uf { get; set; }
        public string ddd { get; set; }
    }
}

Jovem Programador WEB/Models/ErrorViewModel.cs
namespace Jovem_Programador_WEB.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Jovem Programador WEB/Models/Login.cs
namespace Jovem_Programador_WEB.Models
{
    public class Login
    {
        public int Id { get; set; }
        public string Usuario { get; set; }
        public string Senha { get; set; }
    }
}

Jovem Programador WEB/Models/Professor.cs
namespace Jovem_Programador_WEB.Models
{
    public class Professor
    {
        public string Nome { get; set; }
        public string Materia { get; set; }
        public DateTime? DataNascimento { get; set; }
    }
}

Jovem Programador WEB/Controllers/AlunoController.cs
using Jovem_Programador_WEB.Data.Repositorio.Interfaces;
using Jovem_Programador_WEB.Models;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace Jovem_Programador_WEB.Controllers
{
    public class AlunoController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly IAlunoRepositorio _alunoRepositorio;
        public AlunoController(IConfiguration configuration, IAlunoRepositorio alunoRepositorio)
        {
            _configuration = configuration;
            _alunoRepositorio = alunoRepositorio;
        }
        public IActionResult Index()
        {
            var aluno = _alunoRepositorio.BuscarAlunos();
            return View(aluno);
        }
        public IActionResult adicionar()
        {
            return View();
        }

        public IActionResult InserirAluno (Aluno aluno)
        {
            try
            {
                _alunoRepositorio.InserirAluno(aluno);
            }
            catch (Exception ex)
            {
                TempData["MsgErro"] = "Erro ao inserir aluno";
            }
            TempData["MsgSucesso"] = "Aluno adicionado com sucesso";

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> BuscarEndereco(string cep)
        {
            Endereco endereco = new Endereco();

            try
            {
                cep = cep.Replace("-", "");

                using var client = new HttpClient();
                var result = await client.GetAsync(_configuration.GetSection("ApiCep")["BaseUrl"] + cep + "/json");

                if (result.IsSuccessStatusCode)
                {
                    endereco = JsonSerializer.Deserialize<Endereco>(await result.Content.ReadAsStringAsync(), new JsonSerializerOptions() { });
                }
                else
                {
                    ViewData["MsgErro"] = "Erro na busca do endereço!";
                }

            }
            catch (Exception)
            {
                throw;
            }

            return View("Endereco", endereco);
        }
        public IActionResult Editar(int id)
        {
            var aluno = _alunoRepositorio.BuscarId(id);
            return View(aluno);
        }


        public IActionResult EditarAluno(Aluno aluno)
        {
            _alunoRepositorio.EditarAluno(aluno);
            return RedirectToAction("Index");
        }
        public IActionResult ExcluirAluno(int id)
        {
            try
            {
                _alunoRepositorio.ExcluirAluno(id);
                TempData["MsgSucesso"] = "Aluno excluído com sucesso";
            }
            catch (Exception ex)
            {
                TempData["MsgErro"] = "Erro ao excluir aluno";
            }

            return RedirectToAction("Index");
        }


    }
}

Jovem Programador WEB/Controllers/HomeController.cs
using Jovem_Programador_WEB.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Jovem_Programador_WEB.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Jovem Programador WEB/Controllers/LoginController.cs
using Jovem_Programador_WEB.Data.Repositorio.Interfaces;
using Jovem_Programador_WEB.Models;
using Microsoft.AspNetCore.Mvc;

namespace Jovem_Programador_WEB.Controllers
{
    public class LoginController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly ILoginRepositorio _LoginRepositorio;

        public LoginController(IConfiguration configuration, ILoginRepositorio loginRepositorio)
        {
            _configuration = configuration;   
            _LoginRepositorio = loginRepositorio;
        }
        public IActionResult Index()
        {
            return View();
        }
         public IActionResult BuscarLogin(Login login)
        {
            try
            {
               var acesso = _LoginRepositorio.ValidarLogin(login);

                if (acesso != null)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    TempData["MsgErro"] = "Usuário ou senha incorretos!";
                }
            }
            catch (Exception)
            {
                TempData["MsgErro"] = "Erro ao buscar dados do usuário";
            }
            return View("Index");
        }
    }
}

Jovem Programador WEB/Controllers/ProfessorController.cs
using Jovem_Programador_WEB.Models;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace Jovem_Programador_WEB.Controllers
{
    public class ProfessorController : Controller
    {
        private readonly IConfiguration _configuration;
        public ProfessorController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> BuscarEndereco(string cep)
        {
            Endereco endereco = new Endereco();

            try
            {
                cep = cep.Replace("-", "");

                using var client = new HttpClient();
                var result = await client.GetAsync(_configuration.GetSection("ApiCep")["BaseUrl"] + cep + "/json");

                if (result.IsSuccessStatusCode)
                {
                    endereco = JsonSerializer.Deserialize<Endereco>(await result.Content.ReadAsStringAsync(), new JsonSerializerOptions() { });
                }
                else
                {
                    ViewData["MsgErro"] = "Erro na busca do endereço!";
                }
            }

            catch (Exception)
            {
                throw;
            }

            return View("Endereco", endereco);
        }
    }
}

Jovem Programador WEB/Views/Aluno/Adicionar.cshtml
@model Aluno
<form asp-controller="Aluno" asp-action="InserirAluno" method="post">

    <div class="mb-3">
        <label for="nome" class="form-label">Nome</label>
        <input type="text" name="Nome" class="form-control col-md-4" />
    </div>
    <div class="mb-3">
        <label for="idade" class="form-label">Idade</label>
        <input type="text" name="Idade" class="form-control col-md-4" />
    </div>
    <div class="mb-3">
        <label for="matricula" class="form-label">Matrícula</label>
        <input type="text" name="Matricula" class="form-control col-md-4" />
    </div>
    <div class="mb-3">
        <label for="dataNascimento" class="form-label">Data de Nascimento</label>
        <input type="text" name="DataNascimento" class="form-control col-md-4" />
    </div>
    <div class="mb-3">
        <label for="cep" class="form-label">CEP</label>
        <input type="text" name="CEP" class="form-control col-md-4" />
    </div>
    <div class="text-center">
        <button class="btn btn-outline-danger" type="submit">Adicionar</button>
    </div>
</form>

Jovem Programador WEB/Views/Aluno/Editar.cshtml
@model Aluno
<form asp-controller="Aluno" asp-action="EditarAluno" method="post">
    <input type="hidden" asp-for="Id" />

    <div class="mb-3">
        <label for="nome" class="form-label">Nome</label>
        <input type="text" name="Nome" class="form-control col-md-4" asp-for="Nome" />
    </div>
    <div class="mb-3">
        <label for="idade" class="form-label">Idade</label>
        <input type="text" name="Idade" class="form-control col-md-4" asp-for="Idade"/>
    </div>
    <div class="mb-3">
        <label for="matricula" class="form-label">Matrícula</label>
        <input type="text" name="Matricula" class="form-control col-md-4" asp-for="Matricula"/>
    </div>
    <div class="mb-3">
        <label for="dataNascimento" class="form-label">Data de Nascimento</label>
        <input type="text" name="DataNascimento" class="form-control col-md-4" asp-for="DataNascimento"/>
    </div>
    <div class="mb-3">
        <label for="cep" class="form-label">CEP</label>
        <input type="text" name="CEP" class="form-control col-md-4" asp-for="Cep"/>
    </div>
    <div class="text-center">
        <button class="btn btn-primary" type="submit">Alterar</button>
    </div>
</form>

Jovem Programador WEB/Views/Aluno/Endereco.cshtml
@model Endereco

<div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <p>Logradouro: @Html.DisplayFor(endereco => endereco.logradouro)</p>
                <p>Bairro: @Html.DisplayFor(endereco => endereco.bairro)</p>
                <p>UF: @Html.DisplayFor(endereco => endereco.uf)</p>
                <p>DDD: @Html.DisplayFor(endereco => endereco.ddd)</p>
            </div>
            <div class="modal-footer">
                <a class="btn btn-primary" type="button" asp-controller="Aluno" asp-action="Index">Fechar</a>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    <script>
        $(document).ready(function () {
            $('#myModal').modal('show');
        });
    </script>
}

Jovem Programador WEB/Views/Aluno/Index.cshtml
@model List<Aluno>

@if (ViewData["MsgErro"] != null)
{
    <div class="alert-danger">
        @ViewData["MsgErro"]
    </div>
}
@if (ViewData["MsgSucesso"] != null)
{
    <div class="alert-success">
        @ViewData["MsgSucesso"]
    </div>
}

<table class="table">
    <thead>
        <tr>
            
            <th scope="col">Nome</th>
            <th scope="col">Idade</th>
            <th scope="col">Matricula</th>
            <th scope="col">Data Nascimento</th>
            
        </tr>
    </thead>
    <tbody>
        @if (Model != null && Model.Any())
        {
            foreach (Aluno aluno in Model)
            {
                <tr>
                    <td> @aluno.Nome</td>
                    <td> @aluno.Idade</td>
                    <td> @aluno.Matricula</td>
                    <td> @aluno.DataNascimento.Value.ToString("yyyy-MM-dd")</td>



                    <td>
                        <div class="d-grid gap-2 d-md-block">
                            <a type="submit" class="btn btn-outline-secondary" role="button" asp-controller="Aluno" asp-action="BuscarEndereco" asp-route-cep=@aluno.Cep>Endereco</a>
                        </div>
                    </td>

                    <td>
                        <div class="d-grid gap-2 d-md-block">
                            <a type="submit" class="btn btn-outline-secondary" role="button" asp-controller="Aluno" asp-action="Editar" asp-route-id=@aluno.Id>Editar</a>
                        </div>
                    </td>

                    <td>
                        <div class="d-grid gap-2 d-md-block">
                            <a type="submit" class="btn btn-outline-secondary" role="button" asp-controller="Aluno" asp-action="ExcluirAluno" asp-route-id=@aluno.Id>Excluir</a>
                        </div>
                    </td>

                </tr>
            }
        }
        
    </tbody>
</table>

<div class="text-center">
    <a class="btn btn-outline-danger" type="button" asp-controller="Aluno" asp-action="Adicionar">adicionar Aluno</a>
</div>

Jovem Programador WEB/Views/Login/Index.cshtml
@{
    Layout = "_LayoutDeslogado";
}

@if (ViewData["MsgErro"] != null)
{
    <div class="alert-danger">
        @ViewData["MsgErro"]
    </div>
}
@model Login
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>tela de login</title>
    <link href="https://upload.wikimedia.org/wikipedia/commons/8/86/Senac_logo.svg" rel="stylesheet" integrity="sha384-4bw+/aepp/yc94hepvnvgizdgic5+vknbqngchekrqn+ptmohdexuppvndjzqiu9" crossorigin="anonymous">
</head>
<body>
    <div class="container mt-4 ">
        <div class="row align-items-center mx-auto col-lg-5">


            <form class="p-4 p-md-5 border rounded-3 bg-light" asp-controller="Login" asp-action="BuscarLogin" method="post">
                <div class="form-floating mb-3">
                    <input type="usuario" class="form-control" id="inputUsuario" placeholder="Usuario" asp-for="Usuario" />
                    <label for="inputUsuario" class="form-label">Usuário</label>
                </div>

                <div class="form-floating mb-3">
                    <input type="password" class="form-control" id="inputPassword" placeholder="Senha" asp-for="Senha" />
                    <label for="inputSenha" class="form-label">Senha</label>
                </div>

                <button class="w-100 btn btn-lg btn-secondary" role="button">Entrar</button>


            </form>

            <style>
                body {
                    background-color: MidnightBlue; /* Substitua com a cor desejada em hexadecimal, RGB ou nome da cor */
                }
            </style>

            @*   </div>
            </div>
            </div>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-hwwvtgbno3bzjjlyd8ovxjrbzt8cqvspebns5n7c8ivinixgaoxmnlmubnhbgrkm" crossorigin="anonymous"></script>

            </html>*@
</body>

Jovem Programador WEB/Views/Professor/Endereco.cshtml
@model Endereco

<div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <p>Logradouro: @Html.DisplayFor(endereco => endereco.logradouro)</p>
                <p>Bairro: @Html.DisplayFor(endereco => endereco.bairro)</p>
                <p>UF: @Html.DisplayFor(endereco => endereco.uf)</p>
                <p>DDD: @Html.DisplayFor(endereco => endereco.ddd)</p>
            </div>
            <div class="modal-footer">
                <a class="btn btn-primary" type="button" asp-controller="Professor" asp-action="Index">Fechar</a>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    <script>
        $(document).ready(function () {
            $('#myModal').modal('show');
        });
    </script>
}

Jovem Programador WEB/Views/Professor/Index.cshtml
@if (ViewData["MsgErro"] != null)
{
    <div class="alert-danger">
        @ViewData["MsgErro"]
        </div>
}
@if (ViewData["MsgSucesso"] != null)
{
    <div class="alert-success">
        @ViewData["MsgSucesso"]
    </div>
}

<div style="margin-bottom: 19px;"></div>

<style>
    .card-container {
        display: flex;
        justify-content: center;
        margin-left: 20px; /* Adicione o margin-left para mover para a direita */
    }

    .card {
        display: inline-block;
        margin-right: 141px;
        width: 18rem;
    }
</style>

<!--Primeiro card Professor-->
<div class="card" style="width: 18rem;">
    <img src="https://scontent.fbnu4-1.fna.fbcdn.net/v/t39.30808-6/337036917_739859241153214_4841402801339542575_n.jpg?_nc_cat=100&ccb=1-7&_nc_sid=a2f6c7&_nc_eui2=AeFVoPqat7jdkSKlYvyGv1TG2za6ywu9bODbNrrLC71s4KuGbf02z-G9qNZlNEufR4nJfUP_xUpB8dWZP5TehwyF&_nc_ohc=r-pkox0GhiQAX_i0X5X&_nc_ht=scontent.fbnu4-1.fna&oh=00_AfBU4YhoWNWZGKW0SAb-U4vjyMdoR0GeyWLv5OVZs4Bhtw&oe=64FD20A4" class="card-img-top" alt="Imagem do Professor">
    <div class="card-body">
        <h5 class="card-title"><strong>Katia Schmitt Pollheim</strong></h5>
        <p class="card-text"><strong>Especialização:</strong> Desenvolvedor de Software, Professora de TI</p>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item"><strong>MATÉRIAS:</strong></li>
        <li class="list-group-item">Desenvolver aplicações back-end</li>
        <li class="list-group-item">Desenvolver Sistemas</li>
    </ul>
    <div class="card-body">
        <a href="https://www.linkedin.com/in/katia-schmitt-pollheim-a3418b164/" class="card-link">Mais informações</a>
    </div>
</div>

<!--Segundo card Professor-->
<div class="card" style="width: 18rem;">
    <img src="https://scontent.fbnu4-1.fna.fbcdn.net/v/t39.30808-6/343931159_208985464933802_7882312852151703033_n.jpg?stp=cp6_dst-jpg&_nc_cat=100&ccb=1-7&_nc_sid=a2f6c7&_nc_eui2=AeHCHxiC21GIghrq4JvRY__ssqV-bvB9qpiypX5u8H2qmDvJ5FQH3H_wePhXELGF1PZIBejS3vbi11-_hHtNAVyj&_nc_ohc=O5CLEZ961RMAX_vTnod&_nc_ht=scontent.fbnu4-1.fna&oh=00_AfCsyJvRMdOqKC0q4xDR10MzN5-jKoGqTu63hMG0YjYH2Q&oe=64FD62D3" class="card-img-top" alt="Imagem do Professor">
    <div class="card-body">
        <h5 class="card-title"><strong>Nivaldo Pühler</strong></h5>
        <p class="card-text"><strong>Especialização:</strong> Product Manager, Professor, Mentor</p>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item"><strong>MATÉRIAS:</strong></li>
        <li class="list-group-item">Implementar Banco de Dados</li>
        <li class="list-group-item">Elaborar projetos de aplicações</li>
    </ul>
    <div class="card-body">
        <a href="https://www.linkedin.com/in/nivaldopuhler/" class="card-link">Mais informações</a>
    </div>
</div>


<!--Terceiro card Professor-->
<div class="card" style="width: 18rem;">
    <img src="https://scontent.fbnu4-1.fna.fbcdn.net/v/t1.18169-9/27858269_10215642041421666_618809075395381978_n.jpg?_nc_cat=101&ccb=1-7&_nc_sid=09cbfe&_nc_eui2=AeEKmL19ya5hByWc0dj_98BNM-v0myPCMFMz6_SbI8IwU74TriAy5-_JPVwiI049L5Y2jzokttVr3iA77nWfhUCt&_nc_ohc=44UM-JFAf-8AX8do0Xz&_nc_ht=scontent.fbnu4-1.fna&oh=00_AfBO1ajFVA3WVzi2DZsqEXborGK23WxlWjAecZymS_kefw&oe=65202AF1" class="card-img-top" alt="Imagem do Professor">
    <div class="card-body">
        <h5 class="card-title"><strong>Gustavo Guanabara</strong></h5>
        <p class="card-text"><strong>Especialização:</strong>  Professor de TI, Mentor</p>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item"><strong>MATÉRIAS:</strong></li>
        <li class="list-group-item">Estruturar aplicações front-end</li>
        <li class="list-group-item">Publicar aplicações web</li>
    </ul>
    <div class="card-body">
        <a href="https://www.linkedin.com/in/guanabara/" class="card-link">Mais informações</a>
    </div>
</div>

Jovem Programador WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Jovem_Programador_WEB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Jovem_Programador_WEB.styles.css" asp-append-version="true" />
</head>
<body>
    <header>


        <nav class="navbar shadow navbar-dark bg-dark">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample" aria-controls="offcanvasExample">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <img src="https://portal.sc.senac.br/portal/novo/images/logo_senac_branco.svg" class="float-right" width="100">
            </div>
        </nav>



        <div class="offcanvas offcanvas-start d-flex flex-column flex-shrink-0 p-3 text-bg-dark" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel" style="width: 280px;">


            <a href="" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                <img src="https://media.licdn.com/dms/image/D4D03AQEYUq5aj-DOtQ/profile-displayphoto-shrink_400_400/0/1679420538517?e=1699488000&v=beta&t=NsadzkxQRFsZ0qrB1me1u5b4tI5eDLTYiYs_YERDSsk" alt="" width="50" height="50" class="rounded-circle me-4">
                <span class="fs-5 text-black text-">Vinicius Coradini</span>
            </a>
            <hr>
            <ul class="nav nav-pills flex-column mb-auto">
                <li class="nav-item">
                    <a asp-controller="Home" asp-action="Index" class="nav-link text-black" aria-current="page">
                        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="16" fill="currentColor" class="bi bi-house-fill" viewBox="0 0 16 16">
                            <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L8 2.207l6.646 6.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.707 1.5Z" />
                            <path d="m8 3.293 6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6Z" />
                        </svg>
                        Início
                    </a>
                </li>
                <li>
                    <a asp-controller="Aluno" asp-action="Index" class="nav-link text-black">
                        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="16" fill="currentColor" class="bi bi-person-workspace" viewBox="0 0 16 16">
                            <path d="M4 16s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H4Zm4-5.95a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5Z" />
                            <path d="M2 1a2 2 0 0 0-2 2v9.5A1.5 1.5 0 0 0 1.5 14h.653a5.373 5.373 0 0 1 1.066-2H1V3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v9h-2.219c.554.654.89 1.373 1.066 2h.653a1.5 1.5 0 0 0 1.5-1.5V3a2 2 0 0 0-2-2H2Z" />
                        </svg>
                        Aluno
                    </a>
                </li>
                <li>
                    <a asp-controller="Professor" asp-action="Index" class="nav-link text-black">
                        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                            <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z" />
                        </svg>
                        Professor
                    </a>
                </li>

            </ul>
            <hr>
            <div class="dropdown">
                <a href="#" class="d-flex align-items-center text-black text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-gear-fill" viewBox="0 0 16 16">
                        <path d="M9.405 1.05c-.413-1.4-2.397-1.4-2.81 0l-.1.34a1.464 1.464 0 0 1-2.105.872l-.31-.17c-1.283-.698-2.686.705-1.987 1.987l.169.311c.446.82.023 1.841-.872 2.105l-.34.1c-1.4.413-1.4 2.397 0 2.81l.34.1a1.464 1.464 0 0 1 .872 2.105l-.17.31c-.698 1.283.705 2.686 1.987 1.987l.311-.169a1.464 1.464 0 0 1 2.105.872l.1.34c.413 1.4 2.397 1.4 2.81 0l.1-.34a1.464 1.464 0 0 1 2.105-.872l.31.17c1.283.698 2.686-.705 1.987-1.987l-.169-.311a1.464 1.464 0 0 1 .872-2.105l.34-.1c1.4-.413 1.4-2.397 0-2.81l-.34-.1a1.464 1.464 0 0 1-.872-2.105l.17-.31c.698-1.283-.705-2.686-1.987-1.987l-.311.169a1.464 1.464 0 0 1-2.105-.872l-.1-.34zM8 10.93a2.929 2.929 0 1 1 0-5.86 2.929 2.929 0 0 1 0 5.858z" />
                    </svg>
                    <strong></strong>
                </a>
                <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
                    <li><a class="dropdown-item" asp-controller="Login" asp-action="Index">Sair</a></li>
                </ul>
            </div>
        </div>

      

            
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Jovem_Programador_WEB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>